Repository bangdler/airbnb, pull requests merged in 2022-05, with the labels that each got.

#23 Feature/issue1
  airbnb-app/package-lock.json
  airbnb-app/package.json
  airbnb-app/src/App.js
  airbnb-app/src/common/globalStyle.js
  airbnb-app/src/component/AccountMenu.jsx
  airbnb-app/src/component/GNB.jsx
  airbnb-app/src/component/Logo.jsx
  airbnb-app/src/component/MenuTabs.jsx
Labels: feat

#24 Feature/2 코드리뷰 중간 pr
  airbnb-app/package-lock.json
  airbnb-app/package.json
  airbnb-app/src/App.js
  airbnb-app/src/components/search-bar/ResetButton.jsx
  airbnb-app/src/components/search-bar/SearchBar.jsx
  airbnb-app/src/components/search-bar/SearchInput.jsx
  airbnb-app/src/constants/searchBarText.js
Labels: feat

#26 Feature/3
  airbnb-app/src/App.js
  airbnb-app/src/component/GNB.jsx
  airbnb-app/src/component/gnb/AccountMenu.jsx
  airbnb-app/src/component/gnb/GNB.jsx
  airbnb-app/src/component/gnb/Logo.jsx
  airbnb-app/src/component/gnb/MenuTabs.jsx
  airbnb-app/src/component/main-banner/MainBanner.jsx
Labels: feat

#27 Feature/2
  airbnb-app/package-lock.json
  airbnb-app/package.json
  airbnb-app/src/common/globalStyle.js
  airbnb-app/src/component/search-bar/ResetButton.jsx
  airbnb-app/src/component/search-bar/SearchBar.jsx
  airbnb-app/src/component/search-bar/SearchButton.jsx
  airbnb-app/src/component/search-bar/SearchInput.jsx
  airbnb-app/src/constants/searchBarText.js
Labels: feat

#28 Feature/alias
  airbnb-app/config-overrides.js
  airbnb-app/jsconfig.json
  airbnb-app/jsconfig.paths.json
  airbnb-app/package-lock.json
  airbnb-app/package.json
  airbnb-app/src/App.js
  airbnb-app/src/component/gnb/AccountMenu.jsx
  airbnb-app/src/component/gnb/GNB.jsx
  airbnb-app/src/component/gnb/Logo.jsx
  airbnb-app/src/component/gnb/MenuTabs.jsx
  airbnb-app/src/component/main-banner/MainBanner.jsx
  airbnb-app/src/component/search-bar/SearchButton.jsx
  airbnb-app/src/component/search-bar/SearchInput.jsx
  airbnb-app/src/index.js
Labels: feat

#29 Feature/4
  airbnb-app/src/App.js
  airbnb-app/src/component/calender/Calender.jsx
  airbnb-app/src/component/calender/CalenderDateProvider.jsx
  airbnb-app/src/component/calender/CalenderPage.jsx
  airbnb-app/src/component/calender/DateBox.jsx
  airbnb-app/src/component/calender/DatesOfMonth.jsx
  airbnb-app/src/component/calender/Days.jsx
  airbnb-app/src/component/calender/NextButton.jsx
  airbnb-app/src/component/calender/PrevButton.jsx
Labels: feat

#32 Feature/30
  airbnb-app/src/component/header/calender/Calender.jsx
  airbnb-app/src/component/header/calender/CalenderDateProvider.jsx
  airbnb-app/src/component/header/calender/DateBox.jsx
  airbnb-app/src/component/header/calender/DatesOfMonth.jsx
  airbnb-app/src/constants/calenderText.js
Labels: refactor

#35 Feature/6
  airbnb-app/src/component/header/Header.js
  airbnb-app/src/component/header/calender/Calender.jsx
  airbnb-app/src/component/header/gnb/GNB.jsx
  airbnb-app/src/component/header/search-bar/ResetButton.jsx
  airbnb-app/src/component/header/search-bar/SearchBar.jsx
  airbnb-app/src/component/header/search-bar/SearchBarProvider.jsx
  airbnb-app/src/component/header/search-bar/SearchButton.jsx
  airbnb-app/src/component/header/search-bar/SearchInput.jsx
  airbnb-app/src/component/header/search-bar/SearchInputModal.jsx
  airbnb-app/src/component/main-banner/MainBanner.jsx
Labels: feat

#33 Feature/31
  airbnb-app/src/component/header/Header.js
  airbnb-app/src/component/header/calender/Calender.jsx
  airbnb-app/src/component/header/gnb/GNB.jsx
  airbnb-app/src/component/header/search-bar/ResetButton.jsx
  airbnb-app/src/component/header/search-bar/SearchBar.jsx
  airbnb-app/src/component/header/search-bar/SearchBarProvider.jsx
  airbnb-app/src/component/header/search-bar/SearchButton.jsx
  airbnb-app/src/component/header/search-bar/SearchInput.jsx
  airbnb-app/src/component/header/search-bar/SearchInputModal.jsx
  airbnb-app/src/component/main-banner/MainBanner.jsx
Labels: feat, refactor

#36 Feature/34
  airbnb-app/src/component/header/calender/DateBox.jsx
  airbnb-app/src/component/header/calender/DatesOfMonth.jsx
Labels: feat

#38 feat: 검색바 체크인, 체크아웃 날짜 출력 기능 추가
  airbnb-app/src/component/header/calender/CalenderDateProvider.jsx
  airbnb-app/src/component/header/search-bar/ResetButton.jsx
  airbnb-app/src/component/header/search-bar/SearchBar.jsx
  airbnb-app/src/component/header/search-bar/SearchInput.jsx
Labels: feat

#41 feat: 검색바 캘린더 체크인 체크아웃 상태 연동
  airbnb-app/src/component/header/calender/CalenderDateProvider.jsx
  airbnb-app/src/component/header/calender/DateBox.jsx
Labels: feat
